// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeComponentMappingImportMode } from "./CodeComponentMappingImportMode";
import type { CodeComponentMappingProp } from "./CodeComponentMappingProp";
import type { CodeComponentMappingVariantProp } from "./CodeComponentMappingVariantProp";

export type CodeComponentMapping = { id: string, component_id: string, package_name?: string | null, import_path: string, export_name: string, import_mode: CodeComponentMappingImportMode, props: Array<CodeComponentMappingProp>, variant_props?: Array<CodeComponentMappingVariantProp>, docs_url?: string | null, };
