// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeComponentMappingPropType } from "./CodeComponentMappingPropType";
import type { CodeComponentMappingSourceField } from "./CodeComponentMappingSourceField";

export type CodeComponentMappingProp = { name: string, type: CodeComponentMappingPropType, source_node_id: string, source_field: CodeComponentMappingSourceField, default_value: string, };
