// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeComponentMappingPropType } from "./CodeComponentMappingPropType";

export type CodeComponentMappingVariantProp = { name: string, type: CodeComponentMappingPropType, variant_property: string, default_value: string, };
