// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentOverride } from "./ComponentOverride";

export type ComponentInstance = { definition_id: string, variant_id?: string | null, overrides: Array<ComponentOverride>, detached: boolean, };
