// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayoutPadding = { top: number, right: number, bottom: number, left: number, };
