// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayoutSpacingTokens = { gap?: string | null, row_gap?: string | null, column_gap?: string | null, padding_top?: string | null, padding_right?: string | null, padding_bottom?: string | null, padding_left?: string | null, };
