// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutPadding } from "./LayoutPadding";

export type NodeLayoutItem = { margin: LayoutPadding, };
