// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentInstance } from "./ComponentInstance";
import type { NodeConstraints } from "./NodeConstraints";
import type { NodeContent } from "./NodeContent";
import type { NodeKind } from "./NodeKind";
import type { NodeLayout } from "./NodeLayout";
import type { Size } from "./Size";
import type { Style } from "./Style";
import type { Transform } from "./Transform";

export type Node = { id: string, kind: NodeKind, name: string, component_instance?: ComponentInstance | null, layout?: NodeLayout | null, constraints?: NodeConstraints | null, locked: boolean, visible: boolean, children: Array<Node>, transform: Transform, size: Size, style: Style, content: NodeContent, };
