// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutDirection } from "./LayoutDirection";
import type { LayoutMode } from "./LayoutMode";
import type { LayoutPadding } from "./LayoutPadding";

export type NodeLayout = { mode: LayoutMode, direction: LayoutDirection, gap: number, padding: LayoutPadding, };
