// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalConstraint } from "./HorizontalConstraint";
import type { VerticalConstraint } from "./VerticalConstraint";

export type NodeConstraints = { horizontal: HorizontalConstraint, vertical: VerticalConstraint, };
